sudo: true
language: cpp
compiler: gcc
dist: bionic # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # GraphViz
  - sudo apt-get install -qq graphviz

script: 
  - qmake
  - make
  - ./boost_graph_example_2
